x = try:
  class C extends D:
    f() -> 1
catch err:
  class:
    g() -> 1
